### ISSUE TITLE
Regarding the download speed

### ISSUE THREAD

**Issue by Sierkinhane** [Harkame/google-images-downloader#5]
Hi, author, the download speed on my server is slow (10s/img). Any advices to speed up?

**Comment by Harkame** [comment]
Hi

The main reason that the download can be slowed is the maximum wait duration to get the real image url while scraping

By default its 30s, you can reduce this wait duration with option "-w"

Sample : 
```shell
google-images-downloader -q MYQUERY -w 5
```

Explanation : If the script can't retrieve the image url after 5s, it will just get the preview (lower quality than the real image) and continue to the next one

**Comment by Sierkinhane** [comment]
Got it! Thank you.
